### ISSUE TITLE
Bug | Manage error when running leverage out of a repo that has a build.py

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/leverage#10]
## What?
- Manage error when running `leverage` out of a repo that has a `build.py`

```shell
╭─    ~/Binbash/repos/Leverage/ref-architecture ····················································································································································· ✔  at 10:04:04 
╰─ leverage
Traceback (most recent call last):
  File "/usr/local/bin/leverage", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/leverage/leverage.py", line 329, in main
    build(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/leverage/leverage.py", line 40, in build
    module = _load_buildscript(args.file, parser)
  File "/usr/local/lib/python3.9/site-packages/leverage/leverage.py", line 99, in _load_buildscript
    file_path = _find_buildscript()
  File "/usr/local/lib/python3.9/site-packages/leverage/leverage.py", line 79, in _find_buildscript
    root_path = Path(mypath.get_root_path())
  File "/usr/local/lib/python3.9/site-packages/leverage/path.py", line 14, in get_root_path
    git_repo = git.Repo(get_working_path(), search_parent_directories=True)
  File "/usr/local/lib/python3.9/site-packages/git/repo/base.py", line 181, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /Users/exequielbarrirero/Binbash/repos/Leverage/ref-architecture
```

## Why? 
- Simplify and Improve cli UX

**Comment by exequielrafaela** [comment]
@angelofenoglio Thanks for the heads up! Closing then 🤝 ✅
