### ISSUE TITLE
Bug | `leverage --version` fails when OS locale is not english

### ISSUE THREAD

**Issue by angelofenoglio** [binbashar/leverage#229]
## Describe the Bug
Before running most `leverage` commands we need to check is the current directory is part of a `leverage` project. To do this, we simply check if we are within a `git` repository by looking at the output for `git rev-parse --show-toplevel` searching for a specific error. This is done this way because `git`'s error codes are quite generic and make it hard to tell apart the reason for the error with only the error code.
The problem is that we are only taking into consideration the english version of the error message and if it comes to be that the OS is not configured as such we don't catch the error.

## Expected Behavior
The command works as expected regardless of OS locale.

## Steps to Reproduce
1. In any directory run: `leverage --version`

## Output
```
$ leverage --version
Traceback (most recent call last):
  File "/home/ccedeno/.local/bin/leverage", line 5, in <module>
    from leverage import leverage
  File "/home/ccedeno/.local/lib/python3.8/site-packages/leverage/__init__.py", line 18, in <module>
    from leverage.leverage import leverage
  File "/home/ccedeno/.local/lib/python3.8/site-packages/leverage/leverage.py", line 11, in <module>
    from leverage.modules import aws
  File "/home/ccedeno/.local/lib/python3.8/site-packages/leverage/modules/__init__.py", line 3, in <module>
    from .project import project
  File "/home/ccedeno/.local/lib/python3.8/site-packages/leverage/modules/project.py", line 37, in <module>
    PROJECT_ROOT = Path(get_root_path())
  File "/home/ccedeno/.local/lib/python3.8/site-packages/leverage/path.py", line 50, in get_root_path
    return root.strip()
UnboundLocalError: local variable 'root' referenced before assignment
```

## Additional information:
- This should not only affect all leverage versions but also most of leverage commands

**Comment by diego-ojeda-binbash** [comment]
In summary:
- We use `git` to determine the root of the repo
- The error occurs because `git` may not be "properly" configured
- We could use something else to determine the root of the repo, e.g. a dot directory
