### ISSUE TITLE
Bugs |  several `leverage project create` related issues 

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/leverage#92]
@angelofenoglio I'm creating this issue to seen as reference till you can start decoupling them in single ones.

---

:two: :space_invader: leverage credentials

```
OJ  [5:31 PM]
[@Angelo Fenoglio](https://binbashar.slack.com/team/U01T3E2V37Y) te molesto de nuevo, estoy teniendo este error:
$ leverage credentials configure --type BOOTSTRAP
[17:30:50.010] ERROR    Project name has not been set. Exiting.
OJ  [5:32 PM]
mi project.yaml tiene esto:
$ head project.yaml 
project_name: xxxxxxxxxxx
short_name: vp

primary_region: us-east-2
secondary_region: us-west-2

organization:
  accounts:
  - name: management
    email: aws@xxxxxxxxxx.com
OJ  [5:32 PM]
no encuentro q me esta faltando :thinking_face:
Angelo Fenoglio  [5:32 PM]
mmm a ver
OJ  [5:33 PM]
supuestamente busca el short_name
OJ  [5:36 PM]
no tengo nada mas en el nuevo repo q estoy usando:
oj@~/Projects/bb-vp/devops-tf-infra $ ll
total 16
-rw-r--r--  1 oj  staff   378 Apr 26 16:33 README.md
-rw-r--r--  1 oj  staff  2490 May  6 17:28 project.yaml
Angelo Fenoglio  [5:36 PM]
Ah si, no en ese caso no busca el short name
OJ  [5:37 PM]
igual el project_name lo tengo definido
Angelo Fenoglio  [5:37 PM]
Eso me surgio post agregar los containers, defini PROJECT en el build.env
OJ  [5:37 PM]
hace falta el build.env entonces?
Angelo Fenoglio  [5:38 PM]
Justamente cosas como esta tengo que revisar
OJ  [5:38 PM]
ok, por ahora tengo el workaround
OJ  [5:39 PM]
faltan tests para cubrir estas cosas tambien
```

---

[Slack Ref](https://binbashar.slack.com/archives/GG0PJ78J3/p1652096969393149?thread_ts=1652096121.945079&cid=GG0PJ78J3)
:three: :space_invader:  leverage project create

```
OJ  [5:46 PM]
bueno, el project create avanzó un poco mas pero clavó en otro lado
OJ  [5:47 PM]
pareciera q al intentar formatear:
[17:46:13.322] INFO     Reformatting terraform configuration to the standard style.                                                                     
Traceback (most recent call last):
  File "/usr/local/bin/leverage", line 8, in <module>
...
File "/usr/local/lib/python3.9/site-packages/dockerpty/io.py", line 153, in do_write
    written = os.write(self.fd.fileno(), self.buffer)
io.UnsupportedOperation: fileno
OJ  [5:49 PM]
creo q intenta correr esto:
File "/usr/local/lib/python3.9/site-packages/leverage/modules/project.py", line 312, in create
    terraform.start("fmt", "-recursive")
OJ  [5:50 PM]
al menos la estructura de files me la crea y parece estar con los valores reemplazados
```

---
:four::space_invader:  :point_right: Update the bootstrap credentials

https://leverage.binbash.com.ar/first-steps/management-account/#update-the-bootstrap-credentials

```
$ leverage credentials configure --type BOOTSTRAP --skip-access-keys-setup
[22:58:25.001] INFO     Loading configuration file.                                                                                          
[22:58:25.023] INFO     Loading project environment configuration file.                                                                                 
[22:58:25.024] INFO     Loading Terraform common configuration.                                                                                 
[22:58:28.170] INFO     Attempting to fetch organization accounts.                                                                                      
[22:58:32.322] INFO     Configuring assumable roles.                                                                                              
[22:58:32.323] INFO     Backing up account profiles file.                                                                                               
[22:58:32.864] INFO             Configuring profile vp-management-oaar                                                                                  
[22:58:38.675] ERROR    AWS CLI error:                                                                                              
                        usage: aws  <command> <subcommand> [<subcommand> ...]                                                                           
                        To see help text, you can run:                                                                        
                          aws help                                                                      
                          aws <command> help                                                                      
                          aws <command> <subcommand> help                                                                      
                        aws: error: the following arguments are required: value
```

---
[Slack Ref](https://binbashar.slack.com/archives/GG0PJ78J3/p1652097047204229?thread_ts=1652096121.945079&cid=GG0PJ78J3)

:five: :space_invader: replace sso_region with primary_region when rendering the Ref Arch template

```
otra cosita a fixear mas adelante:
sso_region    = "us-east-1"
esto no se reemplaza con la primary region
```

---

:six: :space_invader:  leverage cli Ref arch template considerations

```
otro punto a analizar es el tema del constraint de versiones en el template; versiones de tf y aws provider mayormente
y del template había que quitar esto:
shared_credentials_file = "~/.aws/${var.project}/config"
del bloque de aws provider
```

**Comment by angelofenoglio** [comment]
3 - Fixed
4 - Fixed
5 - In template https://github.com/binbashar/le-tf-infra-aws-template/blob/afdc77b378d2076d8d3ab37918ae2c8f87ef9883/template/config/common.tfvars.template#L33 use https://github.com/binbashar/le-tf-infra-aws-template/blob/afdc77b378d2076d8d3ab37918ae2c8f87ef9883/template/config/common.tfvars.template#L8

**Comment by exequielrafaela** [comment]
- 2️⃣ 👾 leverage credentials: The potential fix we're discussing could rendering the `build.env` from the current project.yml so we'll get the project short also defined here automatically.
- 6️⃣ 👾 leverage cli Ref arch template considerations
  - We should remove `shared_credentials_file = "~/.aws/${var.project}/config"`

**Comment by juanmatias** [comment]
Review 2, 5 and 6

**Comment by juanmatias** [comment]
Regarding 2:
```
# install last RC
╭─    ~/Dev/test/leverage                                                                                                 INT ✘  pyenvleverage 3.10.2  
╰─ pipenv install -i https://test.pypi.org/simple/ leverage==1.7.4rc5
Installing leverage==1.7.4rc5...                                     
✔ Installation Succeeded 
Pipfile.lock (a68613) out of date, updating to (92ef92)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
✔ Success! 
Updated Pipfile.lock (92ef92)!
Installing dependencies from Pipfile.lock (92ef92)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.


# create new project
╭─    ~/Dev/test/leverage                                                                                                     ✔  pyenvleverage 3.10.2  
╰─ mkdir proj004 && cd proj004 && pipenv run leverage project init
[09:46:35.062] INFO     Project template found. Updating.                                                                                                      
[09:46:36.087] INFO     Finished updating template.                                                                                                            
[09:46:36.089] INFO     Initializing git repository in project directory.                                                                                      
[09:46:36.101] INFO     No project configuration file found. Dropping configuration template project.yaml.                                                     
[09:46:36.104] INFO     Project initialization finished.                                                                                                       

# project.yaml edited and now create the credentials
╭─    ~/Dev/test/leverage/proj004    master ?2                                                                      ✔  8s   pyenvleverage 3.10.2  
╰─ pipenv run leverage credentials configure --type BOOTSTRAP
                                                             
[09:51:23.984] INFO     Reading info from project.yaml                                                                                                         
[09:51:24.270] INFO     Loading configuration file.                                                                                                            
[09:51:24.282] INFO     Loading project environment configuration file.                                                                                        
[09:51:24.283] INFO     Loading Terraform common configuration.                                                                                                
[09:51:26.189] INFO     Configuring bootstrap credentials.                                                                                                     
> Select the means by which you'll provide the programatic keys: (Use arrow keys)
 » Path to an access keys file obtained from AWS
   Manually

```

So it seems to be working.

**Comment by juanmatias** [comment]
Regarding 5:
I made the change, here it is the PR, please @angelofenoglio or @diego-ojeda-binbash , could you approve it?
https://github.com/binbashar/le-tf-infra-aws-template/pull/26

**Comment by juanmatias** [comment]
Regarding 5: PR was merged

**Comment by juanmatias** [comment]
Regarding 6:
The key was removed from AWS object in all the templates.
PR here: https://github.com/binbashar/le-tf-infra-aws-template/pull/27
@angelofenoglio @diego-ojeda-binbash do we have a way for testing this change prev to merge?

**Comment by juanmatias** [comment]
If 2 is correctly diagnosed as resolved, 5 is already merged, then as soon 6 is tested/merged this ticket should be eligible to be closed.
CC: @diego-ojeda-binbash @angelofenoglio @exequielrafaela

**Comment by diego-ojeda-binbash** [comment]
> Regarding 6: The key was removed from AWS object in all the templates. PR here: [binbashar/le-tf-infra-aws-template#27](https://github.com/binbashar/le-tf-infra-aws-template/pull/27) @angelofenoglio @diego-ojeda-binbash do we have a way for testing this change prev to merge?

@juanmatias Removing that key shouldn't break anything in the ref arch, perhaps it could only affect other stuff that relies on it (such as tests) but we can address that on case by case basis.

**Comment by juanmatias** [comment]
Ok , @diego-ojeda-binbash ... merged.... so I think 2,5 and 6 are fixed now. If all other items are OK we can close this issue.

**Comment by exequielrafaela** [comment]
@juanmatias thanks for everything, and yes I think we're OK to close this issue so I'll proceed with it :) 

CC: @binbashar/leverage-ref-architecture-aws-admin @binbashar/leverage-ref-architecture-aws-dev
